# Generated by Django 4.0.4 on 2023-07-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_discount_productinventory_productcategory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(auto_created=True, editable=False, null=True, unique=True, verbose_name='Product UUID'),
        ),
    ]
