# Generated by Django 4.0.4 on 2023-07-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Discount Value'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state')),
            ],
            options={
                'verbose_name': 'Top Product',
                'verbose_name_plural': 'Top Products',
                'db_table': 'top_product',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_of_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.ImageField(upload_to='news')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='topproduct',
            index=models.Index(fields=['product'], name='top_product_product_a12d27_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['title'], name='news_title_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['description'], name='news_description_idx'),
        ),
    ]
